version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mentor-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - shared-network
    depends_on: []  # Redis dihapus, jadi kosongkan atau hapus baris ini

networks:
  shared-network:
    external: true
