version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mentor-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - shared-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: shared-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shared-network

volumes:
  mysql_data:

networks:
  shared-network:
    external: true
