version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mentor-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    links:
      - shared-mysql:mysql # alias untuk kemudahan koneksi
    external_links:
      - shared-mysql
    networks:
      - default

networks:
  default:
    name: shared-network
    external: true
