version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mentor-app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8000"
    restart: unless-stopped